kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "webapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: manisha
  template:
    metadata:
      labels:
        app: manisha
    spec:
      containers:
        - name: manisha
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9091
